#!/usr/bin/env python3
"""Experiment 6 - agreement with radiologists' ratings (LDCTIQAC 2023).

Data: LDCTIQAC 2023 training set (Zenodo 10.5281/zenodo.7833096, CC BY 4.0),
1000 abdominal CT images, each with the mean score of five radiologists on a
scale from 0 (worst) to 4 (best). The images were generated by the challenge
organisers from a small number of source slices (reported as 7 patients),
each degraded at several levels of noise and streak artefacts.

Download the training archive from the Zenodo record and unpack it into
data/ldctiqac/, so that data/ldctiqac/LDCTIQAG2023_train/train.json and
data/ldctiqac/LDCTIQAG2023_train/image/ exist.

Decoding. The files hold values in [0, 1]. They are decoded as
HU = 1400 x - 1000, i.e. the window W1400/L-300 stated for the challenge
data; the soft-tissue window W350/L40 is the one the radiologists viewed,
not the encoding. The decoding is checked on the data: the median inside the
body is reported and must be soft tissue. Pixels saturated at 1 (above
400 HU) are flat after the encoding and are left out of the body domain.

Clustering. Images of the same source slice are not independent. File names
do not identify the source, so it is inferred from image similarity: after a
strong low-pass filter, the degraded versions of one slice correlate above
0.999 with each other. Groups are the connected components above 0.995, so
that a source slice is never split (adjacent slices may be merged, which is
conservative); a coarser grouping into 7 anatomical groups approximates the
patients. Confidence intervals resample groups, not images.

What it measures and what it does not: agreement with the quality
**perceived** by radiologists, not with diagnostic performance. The challenge
methods are trained on these scores; RIQE is not.

    .venv/bin/python scripts/exp6_ldctiqac.py
"""

from __future__ import annotations

import os

for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
           "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS"):
    os.environ.setdefault(_v, "1")

import argparse
import concurrent.futures as cf
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image
from scipy.cluster.hierarchy import fcluster, linkage
from scipy.ndimage import gaussian_filter
from scipy.sparse.csgraph import connected_components
from scipy.spatial.distance import squareform
from scipy.stats import pearsonr, spearmanr

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from riqe import niqecfg  # noqa: E402
from riqe.cache import FeatureCache  # noqa: E402
from riqe.extract import MIN_PATCHES_FOR_SCORE, Spec, features_from_hu, luminance, masks_for  # noqa: E402
from riqe.model import RCOND, MVGModel, mahalanobis_mixed  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "ldctiqac" / "LDCTIQAG2023_train"
OUT = ROOT / "experiments"

#: encoding of the distributed files: HU = WIDTH * x + (LEVEL - WIDTH / 2)
WIDTH, LEVEL = 1400.0, -300.0
#: tolerance for considering a pixel saturated
SAT_EPS = 1e-6
#: similarity threshold for grouping images of one source slice
GROUP_CORR = 0.995
N_ANATOMY_GROUPS = 7

_G: dict = {}


def decode(x: np.ndarray) -> np.ndarray:
    return (LEVEL - WIDTH / 2.0) + x * WIDTH


def _init(spec_dict):
    _G["spec"] = Spec(**spec_dict)


def _moments(name):
    x = np.asarray(Image.open(DATA / "image" / name), dtype=np.float32)
    hu = decode(x)
    fov, body = masks_for(hu, None)
    body = body & (x < 1.0 - SAT_EPS)
    pf = features_from_hu(hu, None, _G["spec"], fitting=False, masks=(fov, body))
    f = pf.feat[pf.valid]
    riqe = (None, None) if f.shape[0] < MIN_PATCHES_FOR_SCORE else (f.mean(axis=0), np.cov(f, rowvar=False))
    # the NIQE-parameter baseline: whole image, as NIQE is applied; on the
    # canonical HU mapping and on the files as distributed (255 x)
    niqe_hu = niqecfg.image_moments(luminance(hu, Spec(use_masks=False)))
    niqe_raw = niqecfg.image_moments(255.0 * x)
    return {"name": name, "riqe": riqe, "n_patches": int(f.shape[0]),
            "niqe_hu": niqe_hu[:2], "niqe_raw": niqe_raw[:2],
            "body_median_hu": float(np.median(hu[body])) if body.any() else np.nan,
            "saturated_high": float((x >= 1.0 - SAT_EPS).mean())}


def infer_groups(names) -> tuple[np.ndarray, np.ndarray]:
    """Source-slice groups and anatomical groups from image similarity."""
    X = []
    for n in names:
        x = np.asarray(Image.open(DATA / "image" / n), dtype=np.float32)
        X.append(gaussian_filter(x, 4)[::8, ::8].ravel())
    X = np.asarray(X)
    X = (X - X.mean(1, keepdims=True)) / X.std(1, keepdims=True)
    R = X @ X.T / X.shape[1]
    _, slice_group = connected_components(R > GROUP_CORR, directed=False)
    k = slice_group.max() + 1
    Rg = np.array([[R[np.ix_(slice_group == a, slice_group == b)].mean() for b in range(k)]
                   for a in range(k)])
    Dg = np.clip(1.0 - Rg, 0.0, None)
    np.fill_diagonal(Dg, 0.0)
    anat = fcluster(linkage(squareform(Dg, checks=False), "average"), N_ANATOMY_GROUPS,
                    criterion="maxclust")
    return slice_group, anat[slice_group] - 1


def cluster_boot(frame, fn, group, B=2000, seed=0):
    rng = np.random.default_rng(seed)
    parts = [g for _, g in frame.groupby(group)]
    vals = np.empty(B)
    for b in range(B):
        take = rng.integers(0, len(parts), len(parts))
        vals[b] = fn(pd.concat([parts[i] for i in take], ignore_index=True))
    return [float(np.nanpercentile(vals, 2.5)), float(np.nanpercentile(vals, 97.5))]


def median_boot(v: np.ndarray, B=2000, seed=0):
    """Percentile interval of the median of per-slice values, resampling slices."""
    rng = np.random.default_rng(seed)
    m = np.array([np.median(v[rng.integers(0, len(v), len(v))]) for _ in range(B)])
    return [float(np.percentile(m, 2.5)), float(np.percentile(m, 97.5))]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=28)
    ap.add_argument("--bootstrap", type=int, default=2000)
    args = ap.parse_args()

    ch = json.loads((OUT / "hparam_choice.json").read_text())
    P, C, p = ch["P"], ch["C"], ch["p"]
    scores = json.loads((DATA / "train.json").read_text())
    names = sorted(scores)
    y = np.array([scores[n] for n in names], dtype=float)
    print(f"LDCTIQAC: {len(names)} images, radiologist scores {y.min():g}-{y.max():g}")
    print(f"decoding HU = {WIDTH:g} x + {LEVEL - WIDTH / 2:g}; model P={P} C={C:g} p={p:g}")

    slice_group, anat_group = infer_groups(names)
    sizes = np.bincount(slice_group)
    print(f"source-slice groups: {len(sizes)} (sizes {sizes.min()}-{sizes.max()}, "
          f"median {int(np.median(sizes))}); anatomical groups: {anat_group.max() + 1}")
    (OUT / "ldctiqac_groups.json").write_text(json.dumps({
        "names": names, "source_slice_group": slice_group.tolist(),
        "anatomy_group": anat_group.tolist(), "rule": f"connected components of low-pass "
        f"correlation > {GROUP_CORR}; anatomy: average linkage into {N_ANATOMY_GROUPS}"}, indent=0))

    corpus = pd.read_parquet(ROOT / "corpus" / "corpus.parquet")
    split = json.load(open(ROOT / "corpus" / "split.json"))
    fit = corpus[(corpus["kind"] == "full") & corpus["keep"] & corpus.patient_id.isin(set(split["fit"]))]
    riqe_model = FeatureCache(ROOT / "data" / "features" / f"P{P}_C{C:g}").fit(
        list(fit["path"]), p, n_patients=fit.patient_id.nunique())

    def load(f):
        z = np.load(OUT / f)
        return MVGModel(nu=z["nu"], sigma=z["sigma"], n_patches=0, n_images=0, n_patients=0)

    with cf.ProcessPoolExecutor(args.workers, initializer=_init,
                                initargs=({"P": P, "C": C, "p": None},)) as ex:
        res = list(ex.map(_moments, names, chunksize=8))
    body_hu = np.nanmedian([r["body_median_hu"] for r in res])
    print(f"decoding check: median HU inside the body {body_hu:.0f} (soft tissue expected); "
          f"pixels saturated at 400 HU: {100*np.median([r['saturated_high'] for r in res]):.2f}% (median)")

    def mscore(m, mom):
        return np.nan if mom[0] is None else mahalanobis_mixed(m.nu, m.sigma, mom[0], mom[1], RCOND)

    d = pd.DataFrame({"image": names, "radiologist": y, "source_slice_group": slice_group,
                      "anatomy_group": anat_group})
    d["riqe"] = [mscore(riqe_model, r["riqe"]) for r in res]
    models = {"riqe": "RIQE (CT)"}
    if (OUT / "exp5_photo_model.npz").exists():
        photo = load("exp5_photo_model.npz")
        d["photographic"] = [mscore(photo, r["riqe"]) for r in res]
        models["photographic"] = "Same settings, CC0 photographs"
    if (OUT / "exp5_photo_model_niqecfg.npz").exists():
        nq = load("exp5_photo_model_niqecfg.npz")
        d["niqe_params"] = [mscore(nq, r["niqe_hu"]) for r in res]
        d["niqe_params_raw"] = [mscore(nq, r["niqe_raw"]) for r in res]
        models["niqe_params"] = "NIQE parameters, CC0 photographs (HU mapping)"
        models["niqe_params_raw"] = "NIQE parameters, CC0 photographs (files as distributed)"

    B = args.bootstrap
    rho = lambda col: (lambda f: spearmanr(f[col], f["radiologist"], nan_policy="omit")[0])
    summary = {"P": P, "C": C, "p": p, "n_images": len(names),
               "decoding": {"width": WIDTH, "level": LEVEL, "body_median_hu": float(body_hu)},
               "n_source_slice_groups": int(len(sizes)),
               "n_anatomy_groups": int(anat_group.max() + 1), "models": {}}
    within_by_slice: dict[str, pd.Series] = {}
    for col, label in models.items():
        f = d.dropna(subset=[col])
        r_s = rho(col)(f)
        within = pd.Series({k: spearmanr(g[col], g["radiologist"])[0]
                            for k, g in f.groupby("source_slice_group")
                            if len(g) >= 5 and g["radiologist"].nunique() > 1}).dropna()
        within_by_slice[col] = within
        logo = [rho(col)(f[f.anatomy_group != k]) for k in sorted(f.anatomy_group.unique())]
        summary["models"][col] = {
            "label": label, "n_scored": int(len(f)),
            "n_source_slice_groups": int(f.source_slice_group.nunique()),
            "spearman": float(r_s), "pearson": float(pearsonr(f[col], f["radiologist"])[0]),
            "spearman_ci95_by_source_slice": cluster_boot(f, rho(col), "source_slice_group", B),
            "spearman_ci95_by_anatomy_group": cluster_boot(f, rho(col), "anatomy_group", B, seed=1),
            "spearman_leave_one_anatomy_group_out": [float(min(logo)), float(max(logo))],
            "within_slice_spearman_median": float(np.nanmedian(within)),
            "within_slice_ci95_by_source_slice": median_boot(within.to_numpy(), B),
            "within_slice_groups": int(len(within)),
        }
        s = summary["models"][col]
        print(f"  {label:58s} n={s['n_scored']:4d}  rho {r_s:+.3f}  "
              f"[{s['spearman_ci95_by_source_slice'][0]:+.3f}, {s['spearman_ci95_by_source_slice'][1]:+.3f}] "
              f"by slice, [{s['spearman_ci95_by_anatomy_group'][0]:+.3f}, "
              f"{s['spearman_ci95_by_anatomy_group'][1]:+.3f}] by anatomy; "
              f"within-slice median {s['within_slice_spearman_median']:+.3f}")
    # paired differences in correlation, resampling the same groups
    for other in [c for c in models if c != "riqe"]:
        f = d.dropna(subset=["riqe", other])
        diff = lambda g, o=other: rho("riqe")(g) - rho(o)(g)
        summary["models"][other]["difference_riqe_minus_this"] = {
            "estimate": float(diff(f)),
            "ci95_by_source_slice": cluster_boot(f, diff, "source_slice_group", B, seed=2)}
        # within one source slice, the use RIQE is meant for: median over
        # slices of the paired difference between the two correlations
        w = (within_by_slice["riqe"] - within_by_slice[other]).dropna().to_numpy()
        summary["models"][other]["within_slice_difference_riqe_minus_this"] = {
            "median": float(np.median(w)), "n_slices": int(len(w)),
            "ci95_by_source_slice": median_boot(w, B, seed=3)}

    d.to_csv(OUT / "exp6_ldctiqac_scores.csv", index=False)
    (OUT / "exp6_ldctiqac_summary.json").write_text(json.dumps(summary, indent=1))
    print("\nexpected sign: negative (lower score = closer to the reference; "
          "higher radiologist score = better)")
    print(f"wrote {OUT}/exp6_ldctiqac_{{scores.csv,summary.json}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
